### ISSUE TITLE
Somewhat confusing dependencies

### ISSUE THREAD

**Issue by srcspider** [sindresorhus/gulp-webp#13]
OS: Ubuntu 15.04
```sh
Command failed: JPEG support not compiled. Please install the libjpeg development package before building.
```

Not compiled into what? gulp-webp? 
Why wasnt it exactly compiled with it to begin with? 

---

Concerning this `libjpeg` package, I assume it means this:

```
λ sudo apt-get install libjpeg62-dev
```

*If anyone has stumbled on the same issue; don't install 62-dev write "libjpeg" and hit tab and install the biggest number (62 is just v6.2 of the library)*

Even with that installed you'll still get the error. However if I do,

```
λ npm rm gulp-webp ; npm i gulp-webp

  [ omitting npm messages ]

  ⚠ spawn ENOENT
  ⚠ cwebp pre-build test failed
  ℹ compiling from source
  ✔ cwebp built successfully
gulp-webp@2.3.0 node_modules/gulp-webp
├── modify-error-event@1.0.0 (modify-event@1.0.0)
└── imagemin-webp@3.0.3 (replace-ext@0.0.1, through2@0.6.5, is-cwebp-readable@1.0.1, exec-buffer@2.0.1, cwebp-bin@3.0.0)
```

**Now it finally works.** 

Seems to me it is more then happy to compile with out support for anything.

This is not very intuitive. If possible can you fix this? Maybe some test after the compilation step to check it can actually handle jpeg, png, etc files with instructions on what to install. Right now it works but it probably will fail again as soon as I use a png file somewhere.

**Comment by sindresorhus** [comment]
Can you open this on https://github.com/imagemin/imagemin-webp instead as this plugin is just a thin wrapper above it.

> Why wasnt it exactly compiled with it to begin with?

Compiling on Linux is a nightmare. I'm not surprised at all...

> Seems to me it is more then happy to compile with out support for anything.

How so? It looks like it correctly tried to compile it from source when the pre-compiled binary failed.
