### ISSUE TITLE
Running command npm install gulp-webp --save-dev for error log as below

### ISSUE THREAD

**Issue by prakashsinhab** [sindresorhus/gulp-webp#15]
> cwebp-bin@3.0.0 postinstall c:\12810\gulp\webp.gzip.copy\node_modules\gulp-web
p\node_modules\imagemin-webp\node_modules\cwebp-bin
> node lib/install.js

  ‼ unable to verify the first certificate
  ‼ cwebp pre-build test failed
  i compiling from source
  × Error: ./configure --disable-shared --prefix="c:\12810\gulp\webp.gzip.copy\n
ode_modules\gulp-webp\node_modules\imagemin-webp\node_modules\cwebp-bin\vendor"
--bindir="c:\12810\gulp\webp.gzip.copy\node_modules\gulp-webp\node_modules\image
min-webp\node_modules\cwebp-bin\vendor" && make && make install
Command failed: C:\Windows\system32\cmd.exe /s /c "./configure --disable-shared
--prefix="c:\12810\gulp\webp.gzip.copy\node_modules\gulp-webp\node_modules\image
min-webp\node_modules\cwebp-bin\vendor" --bindir="c:\12810\gulp\webp.gzip.copy\n
ode_modules\gulp-webp\node_modules\imagemin-webp\node_modules\cwebp-bin\vendor""

'.' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:751:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)

**Comment by shinnn** [comment]
Thanks for the report but it should be reported to https://github.com/imagemin/cwebp-bin/issues.

**Comment by prakashsinhab** [comment]
Okay Shinnn, thanks and I would do the needful about it.
