### ISSUE TITLE
Log

### ISSUE THREAD

**Issue by JosefJezek** [sindresorhus/gulp-webp#18]
Could you add log message as `gulp-imagemin`?

`gulp-imagemin: Minified 6 images (saved 9.54 kB - 24.1%)`

**Comment by kevva** [comment]
Wouldn't it be easier to just use `gulp-imagemin` with the `imagemin-webp` plugin?

**Comment by JosefJezek** [comment]
@kevva This combination don't generate separate files with suffix `.webp` :-(

**Comment by sindresorhus** [comment]
Nah, this module is done. Not interested in adding more to it.

**Comment by kevva** [comment]
@JosefJezek, PR is welcome on `gulp-imagemin`. Use the same logic as in https://github.com/imagemin/imagemin/blob/master/index.js#L28.
