### ISSUE TITLE
How to specify output filenames including the original extension?

### ISSUE THREAD

**Issue by shyd** [sindresorhus/gulp-webp#19]
Hi,

currently I have the following gulp4 task:
```js
'use strict';
const gulp = require('gulp');
const webp = require('gulp-webp');

gulp.task('content-images-webp', () =>
  gulp.src('.tmp/content-images-resized/**/*')
    .pipe(webp({quality: 80, method: 6, preset: 'photo'}))
    .pipe(gulp.dest('.tmp/assets/images'))
);
```

The images are correctly being processed. But `test.jpg` will be named `test.webp`.

How can I set things up that the output file will be named `test.jpg.webp`?

Best Regards,
Dennis

**Comment by sindresorhus** [comment]
https://github.com/hparra/gulp-rename
