### ISSUE TITLE
Can we handle Unsupported files

### ISSUE THREAD

**Issue by kapilgp** [sindresorhus/gulp-webp#20]
Hi Sindresorhus,

Thanks for the plugin, I am using this and it's works fine.

But do we have any resolution for handling unsupported files, basically it's creating issues if we are using it with gulp watch and if there is any unsupported files found. It move the scripts to endless loop. 

Error message: 

libpng error: ReadFunc: invalid read length (overflow)!
Error! Could not process file ./dest/dest3/Screenshot-from-2016-08-04-10_47_29.png

**Comment by sindresorhus** [comment]
The latest version ignores unsupported files.
