### ISSUE TITLE
const ext = `file.extname.slice(1).toLowerCase();

### ISSUE THREAD

**Issue by KVAnton-WEB** [sindresorhus/gulp-webp#25]
Everything works, on version gulp-webp@3.0.0
But on gulp-webp@4.0.0 I get this error:
```
gulp-webp/index.js:29
                const ext = `file.extname.slice(1).toLowerCase();
```
gulp@3.9.1
Ubuntu: 18.04 (KDE neon 5.14)
Kernel: Linux 4.20

**Comment by PhakamaniXulu** [comment]
Saved my life , I downgraded to v3.0.0
