### ISSUE TITLE
Cannot read property 'slice' of undefined

### ISSUE THREAD

**Issue by CcRaZyY** [sindresorhus/gulp-webp#26]
Hey, can you help me?
![image](https://user-images.githubusercontent.com/14764134/51798378-ea482900-224b-11e9-939d-d2caa6c70d29.png)
npm 6.6.0
node v10.14.2
gulp CLI version 2.0.1
Local version 3.9.1

**Comment by RigaNik** [comment]
@CcRaZyY I had the same problem. Updated gulp to v4 and error is gone. Cheers

**Comment by CcRaZyY** [comment]
what if I can't update gulp?)

**Comment by RigaNik** [comment]
@CcRaZyY not sure, but I guess one workaround would be that you fork gulp 4, install it and use that .js to run only this gulp task with `node_modules/{your-package-name}/bin/gulp.js webp`. How to chain that processes is up to you.

note: webp is a task name

**Comment by CcRaZyY** [comment]
The best way to simply upgrade to gulp v4..
Thanks. Can be closed

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/gulp-webp/blob/05231b60347c37b8816eed4770bff736921ac913/package.json#L46-L48

**Comment by mahish** [comment]
Or use older version `npm i -D gulp-webp@3` If you cant upgrade to Gulp 4.
